services:
  db:
    image: pgvector/pgvector:pg18  # Специальный образ Postgres с поддержкой векторов
    container_name: kumentor_db
    ports:
      - "5433:5432"                # Пробрасываем порт 5433 на твой компьютер
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty     # Пароль, который ты указал в init_db.py
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql # Данные будут храниться даже после выключения

volumes:
  pgdata: