"""add_favourites_tables_with_constraints_and_defaults

Revision ID: b1eb5bb63b8a
Revises: caac438b54e3
Create Date: 2026-06-02 09:24:59.587291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             ## ДОБАВИТЬ ЭТО
import pgvector.sqlalchemy  ## ДОБАВИТЬ ЭТО


# revision identifiers, used by Alembic.
revision: str = 'b1eb5bb63b8a'
down_revision: Union[str, Sequence[str], None] = 'caac438b54e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
