"""Initial

Revision ID: c7c5330c188d
Revises: 54f802a2a16d
Create Date: 2026-03-13 16:16:56.809715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             ## ДОБАВИТЬ ЭТО
import pgvector.sqlalchemy  ## ДОБАВИТЬ ЭТО


# revision identifiers, used by Alembic.
revision: str = 'c7c5330c188d'
down_revision: Union[str, Sequence[str], None] = '54f802a2a16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('sourceUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'sourceUrl')
    # ### end Alembic commands ###
