"""new skills, qwerty@example.com vacancies and user@example.com applications were  applied

Revision ID: caac438b54e3
Revises: e4913ede5009
Create Date: 2026-05-28 12:32:34.117210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             ## ДОБАВИТЬ ЭТО
import pgvector.sqlalchemy  ## ДОБАВИТЬ ЭТО


# revision identifiers, used by Alembic.
revision: str = 'caac438b54e3'
down_revision: Union[str, Sequence[str], None] = 'e4913ede5009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
