"""add_new_sample_data

Revision ID: fc85080e589b
Revises: b1eb5bb63b8a
Create Date: 2026-06-08 13:07:00.934808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             ## ДОБАВИТЬ ЭТО
import pgvector.sqlalchemy  ## ДОБАВИТЬ ЭТО


# revision identifiers, used by Alembic.
revision: str = 'fc85080e589b'
down_revision: Union[str, Sequence[str], None] = 'b1eb5bb63b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
